[env:genericSTM32F303CB]
platform = ststm32
board = genericSTM32F303CB
framework = cmsis

upload_protocol = stlink

upload_flags = 
    -c
    adapter serial 48FF67066678494942391487
    -c
    set CPUTAPID 0x2ba01477
    -c
    reset_config srst_only

build_flags = -Wl,-Map,output.map
                -Ofast
                -mfpu=fpv4-sp-d16
                -D ARM_MATH_CM4
